---
##### Machine Updates
- hosts: NewHostCentOS, NewHostDebian
  become: yes
  become_user: root
  tasks:
    - name: ping hosts
      ping:

    - name: check OS
      debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}
  
    ### centOS 8
    - name: Upgrade der CentOS Maschienen
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    ### Debian 10
    - name: Upgrade der Debian Maschienen
      apt: update_cache=yes force_apt_get=yes
      when: ansible_distribution_release == 'buster'
