---
##### Install zabbix-agent
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}

### centOS 8
- name: disable SELinux
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: install zabbix centOS 8 rpm file
  yum:
    name: "{{ centos8_link }}"
  when: ansible_os_family == "RedHat"

- name: install zabbix-agent 5.2 for centOS 8
  yum: 
    name: zabbix-agent
    enablerepo: zabbix
    update_cache: true
    state: latest
  when: ansible_os_family == "RedHat"

### Debian 10
- name: download zabbix deb file for Debian 10
  get_url:
    url: "{{ debian10_link }}" 
    dest: "/tmp/{{ debian10_file }}"
  when: ansible_distribution_release == 'debian10'

- name: install zabbix deb in Debian 10
  apt: deb="/tmp/{{ debian10_file }}"
  when: ansible_distribution_release == 'debian10'

- name: install zabbix-agent 4.4 Debian 10
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'debian10'

##### enabled zabbix-agent
- name: enable service zabbix-agent and ensure it is not masked
  systemd:
    name: zabbix-agent
    enabled: yes
    masked: no
  become: yes

##### check zabbix home dir and shell
- name: Make sure a service is stopped
  systemd: state=stopped name=zabbix-agent
  become: yes

- name: check zabbix home dir and shell
  user:
    name: zabbix
    shell: /bin/bash
    home: /etc/zabbix
  become: yes

##### mkdir /etc/zabbix/scripts and rights
- name: mkdir /etc/zabbix/scripts and rights
  file:
    path: /etc/zabbix/scripts
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0700
  become: yes

##### change zabbix_agentd.conf
- name: change zabbix_agentd.conf Hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Hostname=Zabbix server'
    line: "Hostname={{ ansible_hostname }}"
  become: yes
    
- name: change zabbix_agentd.conf ServerActive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'ServerActive=127.0.0.1'
    line: "ServerActive={{ zbx_srv }}"
  become: yes

- name: change zabbix_agentd.conf Server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Server=127.0.0.1'
    line: "Server={{ zbx_srv }}"
  become: yes

- name: change zabbix_agentd.conf EnableRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
  become: yes

- name: change zabbix_agentd.conf LogRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# LogRemoteCommands=0'
    line: 'LogRemoteCommands=1'

### Starting zabbix-agent
- name: Make sure a service is started
  systemd: state=started name=zabbix-agent
  become: yes
